// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'add-button-label'
  | 'column-neg-label'
  | 'column-pos-label'
  | 'delete-button'
  | 'field-comment'
  | 'field-source-pages'
  | 'field-target-pages'
  | 'graph-empty'
  | 'graph-window-title'
  | 'menu-graph'
  | 'missing-item'
  | 'no-incoming'
  | 'no-outgoing'
  | 'section-head-text'
  | 'section-incoming-title'
  | 'section-outgoing-title'
  | 'section-sidenav-tooltip'
  | 'stance-0'
  | 'stance-m'
  | 'stance-mm'
  | 'stance-p'
  | 'stance-pp';
