// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "stancePalette": string;
      "displayPaneAuthor": boolean;
      "displayPaneYear": boolean;
      "displayPaneTitle": boolean;
      "displayGraphAuthor": boolean;
      "displayGraphYear": boolean;
      "displayGraphTitle": boolean;
      "graphColorByType": boolean;
      "graphExportTransparent": boolean;
      "graphLinkDistance": number;
      "graphHighlightTags": string;
      "graphShowSearch": boolean;
      "graphShowFilters": boolean;
      "graphShowTags": boolean;
      "graphShowSizeToggle": boolean;
      "graphShowLinkDistance": boolean;
      "graphShowTimeline": boolean;
      "readerSelectionButton": boolean;
      "stanceControlCompact": boolean;
      "copyRefsToGroup": boolean;
    };
  }
}
